version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm test
      - store_test_results:
          path: coverage/clover.xml

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test