version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: sudo npm install ask-cli -g
      - run: npm install
      - run:
          name: test
          command: npm test
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - run: npm run test.smapi
      - run: npm run coverage
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
  test-babel:
      docker:
        - image: circleci/node:8
      steps:
        - checkout
        - run: npm install
        - run: npm run test.babel
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - test-babel