name: Publish RC into NPM registry
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
        with:
          ref: research-githubActionPublish-by_max
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm version
