name: Publish RC into NPM registry
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
        with:
          ref: research-githubActionPublish-by_max
      - name: Config GIT user and email
        env: 
          CI_COMMIT_AUTHOR: Maximo Rosales Diaz
        run: |
          git config user.name "Maximo Rosales Diaz"
          git config user.email "max@bespoken.io"
      - name: Setup node version 10.x
        uses: actions/setup-node@v3
        with:
          node-version: '10.x'
          registry-url: 'https://registry.npmjs.org'
      - name: NPM increment RC version
        run: npm version $(node -e "require('./publishing-toolkit.js').printNextRcVersion()")
      - name: NPM Build
        run: |
          npm ci
          npm run babel
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      - name: NPM publish into registry
        run: |
          npm publish --tag alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      - name: Push changes
        run: |
          git push
  
  
