name: Publish ALPHA into NPM registry
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
      - name: Config GIT user and email
        run: |
          git config user.name "$(git log -1 --pretty=format:'%an')"
          git config user.email "$(git log -1 --pretty=format:'%ae')"
      - name: Setup node version 10.x
        uses: actions/setup-node@v3
        with:
          node-version: '10.x'
          registry-url: 'https://registry.npmjs.org'
      - name: NPM increment version for alpha
        run: npm version $(node -e "require('./publishing-toolkit.js').printNextAlphaVersion()")
      - name: GIT Pushing changes
        run: |
          git push
          git push --tags
      - name: NPM Build
        run: |
          npm ci
          npm run babel
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      - name: NPM publish into registry
        run: |
          npm publish --tag alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}